{% set name = "genestboost" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/genestboost-{{ version }}.tar.gz
  sha256: a466a4629146f9f36f7452fca922055b35596e456bfd646a9d007535a01641d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    - numpy ==1.*,>=1.18.5
    - python >=3.7,<3.10
    - scipy ==1.*,>=1.4.1

test:
  imports:
    - genestboost
    - genestboost.link_functions
    - genestboost.loss_functions
    - genestboost.utils
    - genestboost.weak_learners
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/btcross26/genestboost
  summary: General boosting framework for any regression estimator
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: |
    genestboost is an ML boosting library that separates the modeling algorithm
    from the boosting algorithm. The result is that you can boost any generic
    regression model, not just trees. Build a forward-thinking
    (forward-propagating) neural network if you wish, or build an ensemble of
    support vector machines if you would so desire. Mix and match link and loss
    functions at will.
  doc_url: https://btcross26.github.io/genestboost/build/html/index.html
  dev_url: https://github.com/btcross26/genestboost

extra:
  recipe-maintainers:
    - btcross26
